trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Initialize Terraform
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure_connection'
    backendAzureRm: true
    backendAzureRmStorageAccountName: 'terraform524'
    backendAzureRmContainerName: 'kubecontainer'
    backendAzureRmKey: 'terraform.tfstate'
    backendAzureRmResourceGroupName: 'ap_rg1'
    backendAzureRmSubscriptionId: '606e824b-aaf7-4b4e-9057-b459f6a4436d'
    backendAzureRmTenantId: '104e77d4-81e7-4c16-ab44-935220bed6dd'

# Apply Terraform configuration
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'azure_connection'
    workingDirectory: '$(System.DefaultWorkingDirectory)/gweb/kubcluster_files'
    commandOptions: '-auto-approve'
