apiVersion : apps/v1
kind: Deployment
metadata:
  name: simple-webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webpage
  template:
    metadata:
      labels:
        app: simple-webpage 
    spec:
      containers:
        - name: simple-webpage 
          image: new2continerregistry.azurecr.io/csimple-webpage 
          ports:
          - containerPort: 80
--------

apiVersion: v1
kind: Service
metadata:
    name: simple-webpage 
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: simple-webpage 